# Generated by Django 4.0.5 on 2022-06-06 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_todoilist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='Id',
        ),
        migrations.AddField(
            model_name='login',
            name='Password',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='Salt',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='Email',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
